### ISSUE TITLE
Specific song fails to play

### ISSUE THREAD

**Issue by MrGundum** [jumpers775/Tempo#1]
Trying to play congradulations pewdiepie

`[2023-01-15 21:13:03] [ERROR   ] discord.ui.view: Ignoring exception in view <SelectView timeout=180 children=1> for item <SelectSong placeholder='Select an option' min_values=1 max_values=1 disabled=False options=[<SelectOption label='1) Congratulations' value='1) Congratulations' description='By PewDiePie' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='2) Congratulations' value='2) Congratulations' description='By Pewdiepie & Roomie & Boyinaband - Topic' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='3) Making the song with PewDiePie (Congratulations BTS)' value='3) Making the song with PewDiePie (Congratulations BTS)' description='By Boyinaband' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='4) Congratulations' value='4) Congratulations' description='By Pewdiepie & Roomie & Boyinaband - Topic' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='5) Pewdiepie - Congratulations/Lyrics' value='5) Pewdiepie - Congratulations/Lyrics' description='By Medicine' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='6) bitch lasagna' value='6) bitch lasagna' description='By PewDiePie' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='7) My friends expose me..  /r/quityourbs/ #26 [REDDIT REVIEW]' value='7) My friends expose me..  /r/quityourbs/ #26 [REDDIT REVIEW]' description='By PewDiePie' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='8) Pewdiepie - Congratulations (Lyrics / Lyric Video) ft. Roomie, Boyinaband' value='8) Pewdiepie - Congratulations (Lyrics / Lyric Video) ft. Roomie, Boyinaband' description='By iamaashif' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='9) College Kids React To PewDiePie - Congratulations' value='9) College Kids React To PewDiePie - Congratulations' description='By REACT' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>, <SelectOption label='10) Congratulations 2' value='10) Congratulations 2' description='By FlyingKitty' emoji=<PartialEmoji animated=False name='🎧' id=None> default=False>]>
Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ui\view.py", line 425, in _scheduled_task
    await item.callback(interaction)
  File "C:\Users\James\Downloads\Tempo-main\bot.py", line 167, in callback
    bot.queueorder[interaction.guild.id].append(entry)
IndexError: list index out of range
`

**Comment by lucamignatti** [comment]
Sorry for the late reply, i have been quite busy lately. 

I have tested this on my machine and it plays fine, however thats not to say there isnt an issue somewhere. The title suggests  this issue only occurs for that specific song, is this case? could you send the youtube link of that song if so. This looks like its not finding your guilds queueorder list, which should affect all songs. Also could you please let me know if shuffle is enabled.

**Comment by lucamignatti** [comment]
Closed due to my inability to reproduce, and inactivity.
