### ISSUE TITLE
Issue running

### ISSUE THREAD

**Issue by koolkiwi** [jumpers775/Tempo#8]
Installed everything & got the bot token added after running. However after that the bot.py closes and when I open it again it runs and then closes. There is nowhere to write the $sync command. 

I added the bot to my server but no bot joined and no commands are there.

Thanks

**Comment by lucamignatti** [comment]
The bot will be added regardless of its running or not, so you likely invited it wrong. You will have to run $sync to add the commands once it's there too.

**Comment by koolkiwi** [comment]
Thanks for that/ Getting stuck on the url redirect unsure what to put it as
